/** Made by Richard Sabrsula
*	Builds the UI for the customer view and has the appropriate functions.
*/
package assign4;
import static assign4.ConsoleUserInterface.dealership;
import java.awt.*;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * @author Richard
 */
public class CustomerViewUI extends JFrame {

    /**
     * Creates new form CustomerViewUI
     */
    public CustomerViewUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        noResultsFrame = new javax.swing.JDialog();
        noResultsTitle = new javax.swing.JLabel();
        noResultsExit = new javax.swing.JButton();
        noResultsLabel = new javax.swing.JLabel();
        searchResults = new javax.swing.JDialog();
        searchResultsTitle = new javax.swing.JLabel();
        searchResultsExit = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        noRadioPushed = new javax.swing.JDialog();
        buttonErrorTitle = new javax.swing.JLabel();
        buttonErrorLabel = new javax.swing.JLabel();
        errorExit = new javax.swing.JButton();
        messageFieldEmpty = new javax.swing.JDialog();
        messageEmptyTitle = new javax.swing.JLabel();
        messageEmptyLabel = new javax.swing.JLabel();
        messageFieldsEmptyExit = new javax.swing.JButton();
        messageSuccess = new javax.swing.JDialog();
        messageSuccessTitle = new javax.swing.JLabel();
        messageSuccessLabel1 = new javax.swing.JLabel();
        messageSuccessLabel2 = new javax.swing.JLabel();
        messageSuccessExit = new javax.swing.JButton();
        dealershipSoftwareTitle = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchDealershipTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vinPane = new javax.swing.JTextPane();
        vinLabel = new javax.swing.JLabel();
        searchSeparator = new javax.swing.JSeparator();
        searchDealershipTitleProp = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        makePane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelPane = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        yearPane = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        lowPricePane = new javax.swing.JTextPane();
        modelLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        priceBetweenLabel = new javax.swing.JLabel();
        andLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        highPricePane = new javax.swing.JTextPane();
        carRadio = new javax.swing.JRadioButton();
        truckRadio = new javax.swing.JRadioButton();
        motorRadio = new javax.swing.JRadioButton();
        searchDatabaseVIN = new javax.swing.JButton();
        searchDatabaseProp = new javax.swing.JButton();
        exitCustView = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();
        sendMessageTitle = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        messagePane = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        namePane = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        emailPane = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        phonePane = new javax.swing.JTextPane();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        noResultsFrame.setAlwaysOnTop(true);

        noResultsTitle.setText("Results:");

        noResultsExit.setText("Exit");
        noResultsExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noResultsExitActionPerformed(evt);
            }
        });

        noResultsLabel.setText("No vehicles found.");

        javax.swing.GroupLayout noResultsFrameLayout = new javax.swing.GroupLayout(noResultsFrame.getContentPane());
        noResultsFrame.getContentPane().setLayout(noResultsFrameLayout);
        noResultsFrameLayout.setHorizontalGroup(
            noResultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noResultsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noResultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noResultsFrameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(noResultsLabel))
                    .addComponent(noResultsTitle))
                .addGap(0, 79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noResultsFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noResultsExit)
                .addContainerGap())
        );
        noResultsFrameLayout.setVerticalGroup(
            noResultsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noResultsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noResultsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noResultsLabel)
                .addGap(29, 29, 29)
                .addComponent(noResultsExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchResultsTitle.setText("Search results:");

        searchResultsExit.setText("Exit");
        searchResultsExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchResultsExitActionPerformed(evt);
            }
        });

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane18.setViewportView(resultsTable);

        javax.swing.GroupLayout searchResultsLayout = new javax.swing.GroupLayout(searchResults.getContentPane());
        searchResults.getContentPane().setLayout(searchResultsLayout);
        searchResultsLayout.setHorizontalGroup(
            searchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchResultsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchResultsExit))
                    .addGroup(searchResultsLayout.createSequentialGroup()
                        .addComponent(searchResultsTitle)
                        .addGap(0, 347, Short.MAX_VALUE))
                    .addGroup(searchResultsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchResultsLayout.setVerticalGroup(
            searchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResultsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchResultsExit)
                .addContainerGap())
        );

        buttonErrorTitle.setText("Error");

        buttonErrorLabel.setText("You must select a vehicle type (car, truck, or motorcycle).");

        errorExit.setText("Exit");
        errorExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout noRadioPushedLayout = new javax.swing.GroupLayout(noRadioPushed.getContentPane());
        noRadioPushed.getContentPane().setLayout(noRadioPushedLayout);
        noRadioPushedLayout.setHorizontalGroup(
            noRadioPushedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noRadioPushedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noRadioPushedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noRadioPushedLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonErrorLabel))
                    .addComponent(buttonErrorTitle))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noRadioPushedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorExit)
                .addContainerGap())
        );
        noRadioPushedLayout.setVerticalGroup(
            noRadioPushedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noRadioPushedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonErrorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(errorExit)
                .addContainerGap())
        );

        messageEmptyTitle.setText("Error");

        messageEmptyLabel.setText("No fields can be empty when sending a message to the dealership.");

        messageFieldsEmptyExit.setText("Exit");
        messageFieldsEmptyExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFieldsEmptyExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageFieldEmptyLayout = new javax.swing.GroupLayout(messageFieldEmpty.getContentPane());
        messageFieldEmpty.getContentPane().setLayout(messageFieldEmptyLayout);
        messageFieldEmptyLayout.setHorizontalGroup(
            messageFieldEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageFieldEmptyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageFieldEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageFieldEmptyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(messageEmptyLabel))
                    .addComponent(messageEmptyTitle))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messageFieldEmptyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageFieldsEmptyExit)
                .addContainerGap())
        );
        messageFieldEmptyLayout.setVerticalGroup(
            messageFieldEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageFieldEmptyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageEmptyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageEmptyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(messageFieldsEmptyExit)
                .addContainerGap())
        );

        messageSuccessTitle.setText("Success!");

        messageSuccessLabel1.setText("Your message has successfully been sent to the dealership!");

        messageSuccessLabel2.setText("A customer rep will reply shortly.");

        messageSuccessExit.setText("Exit");
        messageSuccessExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSuccessExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageSuccessLayout = new javax.swing.GroupLayout(messageSuccess.getContentPane());
        messageSuccess.getContentPane().setLayout(messageSuccessLayout);
        messageSuccessLayout.setHorizontalGroup(
            messageSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageSuccessTitle)
                    .addGroup(messageSuccessLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(messageSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(messageSuccessExit)
                            .addGroup(messageSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(messageSuccessLabel2)
                                .addComponent(messageSuccessLabel1)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        messageSuccessLayout.setVerticalGroup(
            messageSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageSuccessTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageSuccessLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageSuccessLabel2)
                .addGap(18, 18, 18)
                .addComponent(messageSuccessExit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dealershipSoftwareTitle.setText("Dealership Software: Customer View");

        searchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchDealershipTitle.setText("Search the dealership's database for a vehicle by VIN.");

        jScrollPane1.setViewportView(vinPane);

        vinLabel.setText("VIN:");

        searchDealershipTitleProp.setText("Search the dealership's database for a vehicle by properties.");

        makeLabel.setText("Make:");

        jScrollPane2.setViewportView(makePane);

        jScrollPane3.setViewportView(modelPane);

        jScrollPane4.setViewportView(yearPane);

        jScrollPane5.setViewportView(lowPricePane);

        modelLabel.setText("Model:");

        yearLabel.setText("Year:");

        priceBetweenLabel.setText("Price between $");

        andLabel.setText(" and $");

        jScrollPane6.setViewportView(highPricePane);

        buttonGroup1.add(carRadio);
        carRadio.setText("Car");

        buttonGroup1.add(truckRadio);
        truckRadio.setText("Truck");

        buttonGroup1.add(motorRadio);
        motorRadio.setText("Motorcycle");

        searchDatabaseVIN.setText("Search");
        searchDatabaseVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabaseVINActionPerformed(evt);
            }
        });

        searchDatabaseProp.setText("Search");
        searchDatabaseProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabasePropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchSeparator))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchDealershipTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(vinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchDatabaseVIN))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addComponent(priceBetweenLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(andLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(carRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(truckRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(motorRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchDatabaseProp))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchDealershipTitleProp)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(makeLabel)
                                            .addComponent(modelLabel)
                                            .addComponent(yearLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(searchDealershipTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vinLabel)
                    .addComponent(searchDatabaseVIN))
                .addGap(26, 26, 26)
                .addComponent(searchSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDealershipTitleProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(andLabel)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(makeLabel)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(modelLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(yearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(priceBetweenLabel))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carRadio)
                    .addComponent(truckRadio)
                    .addComponent(motorRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(searchDatabaseProp)
                .addContainerGap())
        );

        exitCustView.setText("Exit");
        exitCustView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitCustViewActionPerformed(evt);
            }
        });

        messagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        messagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sendMessageTitle.setText("Send a message to the dealership.");

        messagePane.setColumns(20);
        messagePane.setRows(5);
        messagePane.setText("gngng");
        jScrollPane7.setViewportView(messagePane);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");

        jScrollPane15.setViewportView(namePane);

        jScrollPane16.setViewportView(emailPane);

        jScrollPane17.setViewportView(phonePane);

        emailLabel.setText("Email:");

        phoneLabel.setText("Phone #:");

        messageLabel.setText("Message:");

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(messagePanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(messagePanelLayout.createSequentialGroup()
                                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nameLabel)
                                            .addComponent(emailLabel)
                                            .addComponent(phoneLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(jScrollPane17)
                                            .addComponent(jScrollPane15)))
                                    .addGroup(messagePanelLayout.createSequentialGroup()
                                        .addComponent(messageLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(sendMessageTitle))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendButton)
                        .addGap(10, 10, 10))))
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addComponent(sendMessageTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagePanelLayout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealershipSoftwareTitle)
                            .addComponent(exitCustView))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dealershipSoftwareTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitCustView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * @param searchDatabaseVIN button pushed
    * Searches database for VIN and outputs appropriate response.
    */
    private void searchDatabaseVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabaseVINActionPerformed
        //sets cursor to waiting
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String vin = vinPane.getText();
        final Vehicle v = dealership.getVehInv().searchInventory(vin);
        messagePane.setText("works");
        //if vehicle exists, output it to table, according to type
        if (v != null) {
            //type PassengerCar
            if(v instanceof PassengerCar) {
                PassengerCar car = (PassengerCar) v;
                String make = car.getMake();
                String model = car.getModel();
                int year = car.getYear();
                int mileage = car.getMileage();
                float price = car.getPrice();
                String body = car.getBodyStyle();
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {make, model, year, mileage, price, vin, body}
                    },
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra info"
                    }
                    ));
                //resizes and centers window popup with results
                searchResults.setBounds(100, 100, 500, 300);
                searchResults.setLocationRelativeTo(this);
                //Type Truck
            } else if (v instanceof Truck) {
                Truck truck = (Truck) v;
                String make = truck.getMake();
                String model = truck.getModel();
                int year = truck.getYear();
                int mileage = truck.getMileage();
                float price = truck.getPrice();
                float length = truck.getLength();
                float load = truck.getMaxLoadWeight();
                String extra = "Length(ft): " + length + " Max Load(lbs): " + load;
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {make, model, year, mileage, price, vin, extra}
                    },
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra info"
                    }
                    ));
                //resizes and centers window popup with results
                resultsTable.getColumn("Extra info").setWidth(350);
                resultsTable.getColumn("Extra info").setPreferredWidth(350);
                searchResults.setBounds(100, 100, 700, 300);
                searchResults.setLocationRelativeTo(this);
                //Type Motorcycle
            } else {
                Motorcycle motor = (Motorcycle) v;
                String make = motor.getMake();
                String model = motor.getModel();
                int year = motor.getYear();
                int mileage = motor.getMileage();
                float price = motor.getPrice();
                float disp = motor.getDisplacement();
                String type = motor.getType();
                String extra = "Displacement: " + disp + " Engine type: " + type;
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {make, model, year, mileage, price, vin, extra}
                    },
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra info"
                    }
                    ));
                //resizes and centers windows popup with results
                resultsTable.getColumn("Extra info").setWidth(350);
                resultsTable.getColumn("Extra info").setPreferredWidth(350);
                searchResults.setBounds(100, 100, 800, 300);
                searchResults.setLocationRelativeTo(this);
            }
            //Reverts cursor, shows reults
            this.setCursor(Cursor.getDefaultCursor());
            searchResults.setVisible(true);
            v.print();
        } else {
            //If vehicle doesn't exit, display proper message
            this.setCursor(Cursor.getDefaultCursor());
            noResultsFrame.setBounds(100, 100, 235, 150);
            noResultsFrame.setLocationRelativeTo(this);
            noResultsFrame.setVisible(true);
        }
    }//GEN-LAST:event_searchDatabaseVINActionPerformed

    /* 
    * @param searchDatabaseProp button pushed
    * Searched database for vehicle based on type and properties.
    */
    private void searchDatabasePropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabasePropActionPerformed
        //if Vehicle type is Passengercar
        if(carRadio.isSelected()) {
            //Start waiting cursor
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String make = makePane.getText();
            String model = modelPane.getText();
            String year = yearPane.getText();
            String priceLow = lowPricePane.getText();
            String priceHigh = highPricePane.getText();
            //search database for matching cases
            try {
                Set<Vehicle> vehicles = dealership.getVehInv().searchInventory(1, make, model, year, priceLow, priceHigh);
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [vehicles.size()][] ,
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra Info"
                    }
                    ));
                int i = 0;
                //for all matching cases, go through table row by row and add
                for (Vehicle v : vehicles) {
                    PassengerCar car = (PassengerCar) v;
                    resultsTable.setValueAt(v.getMake(), i, 0);
                    resultsTable.setValueAt(v.getModel(), i, 1);
                    resultsTable.setValueAt(v.getYear(), i, 2);
                    resultsTable.setValueAt(v.getMileage(), i, 3);
                    resultsTable.setValueAt(v.getPrice(), i, 4);
                    resultsTable.setValueAt(v.getVin(), i, 5);
                    resultsTable.setValueAt(car.getBodyStyle(), i, 6);
                    i++;
                }
                //no matching cases, show appropriate message
                if(vehicles.isEmpty()) {
                    noResultsFrame.setBounds(100, 100, 235, 150);
                    noResultsFrame.setLocationRelativeTo(this);
                    noResultsFrame.setVisible(true);
                } else {
                    //display results
                    searchResults.setBounds(100, 100, 500, 300);
                    searchResults.setLocationRelativeTo(this);
                    searchResults.setVisible(true);
                }
            } catch (BadInputException ex) {
                Logger.getLogger(CustomerViewUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //revert cursor
            this.setCursor(Cursor.getDefaultCursor());
            //if Vehicle type is Truck
        } else if(truckRadio.isSelected()) {
            //change cursor to waiting
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String make = makePane.getText();
            String model = modelPane.getText();
            String year = yearPane.getText();
            String priceLow = lowPricePane.getText();
            String priceHigh = highPricePane.getText();
            //search database for matching cases
            try {
                Set<Vehicle> vehicles = dealership.getVehInv().searchInventory(2, make, model, year, priceLow, priceHigh);
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [vehicles.size()][] ,
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra Info"
                    }
                    ));
                int i = 0;
                //put matching cases into table row by row
                for (Vehicle v : vehicles) {
                    Truck truck = (Truck) v;
                    resultsTable.setValueAt(v.getMake(), i, 0);
                    resultsTable.setValueAt(v.getModel(), i, 1);
                    resultsTable.setValueAt(v.getYear(), i, 2);
                    resultsTable.setValueAt(v.getMileage(), i, 3);
                    resultsTable.setValueAt(v.getPrice(), i, 4);
                    resultsTable.setValueAt(v.getVin(), i, 5);
                    String extra = "Length (ft): " + truck.getLength() + " Max load(lbs): " + truck.getMaxLoadWeight();
                    resultsTable.setValueAt(extra, i, 6);
                    i++;
                }
                resultsTable.getColumn("Extra Info").setWidth(350);
                resultsTable.getColumn("Extra Info").setPreferredWidth(350);
                //if no matching cases, display appropriate message
                if(vehicles.isEmpty()) {
                    noResultsFrame.setBounds(100, 100, 235, 150);
                    noResultsFrame.setLocationRelativeTo(this);
                    noResultsFrame.setVisible(true);
                //display results
                } else {
                    searchResults.setBounds(100, 100, 700, 300);
                    searchResults.setLocationRelativeTo(this);
                    searchResults.setVisible(true);
                }
            } catch (BadInputException ex) {
                Logger.getLogger(CustomerViewUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //revert cursor
            this.setCursor(Cursor.getDefaultCursor());
        //Vehicle type Motorcycle
        } else if(motorRadio.isSelected()) {
            //set cursor to waiting
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String make = makePane.getText();
            String model = modelPane.getText();
            String year = yearPane.getText();
            String priceLow = lowPricePane.getText();
            String priceHigh = highPricePane.getText();
            //try to find matching cases in database
            try {
                Set<Vehicle> vehicles = dealership.getVehInv().searchInventory(3, make, model, year, priceLow, priceHigh);
                resultsTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [vehicles.size()][] ,
                    new String [] {
                        "Make", "Model", "Year", "Mileage", "Price", "VIN", "Extra Info"
                    }
                    ));
                int i = 0;
                //add matching cases to table row by row
                for (Vehicle v : vehicles) {
                    Motorcycle motor = (Motorcycle) v;
                    resultsTable.setValueAt(v.getMake(), i, 0);
                    resultsTable.setValueAt(v.getModel(), i, 1);
                    resultsTable.setValueAt(v.getYear(), i, 2);
                    resultsTable.setValueAt(v.getMileage(), i, 3);
                    resultsTable.setValueAt(v.getPrice(), i, 4);
                    resultsTable.setValueAt(v.getVin(), i, 5);
                    String extra = "Displacement (cc): " + motor.getDisplacement() + " Type: " + motor.getType();
                    resultsTable.setValueAt(extra, i, 6);
                    i++;
                }
                resultsTable.getColumn("Extra Info").setWidth(350);
                resultsTable.getColumn("Extra Info").setPreferredWidth(350);
                //if no matching cases display appropriate message
                if(vehicles.isEmpty()) {
                    noResultsFrame.setBounds(100, 100, 235, 150);
                    noResultsFrame.setLocationRelativeTo(this);
                    noResultsFrame.setVisible(true);
                //display results
                } else {
                    searchResults.setBounds(100, 100, 800, 300);
                    searchResults.setLocationRelativeTo(this);
                    searchResults.setVisible(true);
                }
            } catch (BadInputException ex) {
                Logger.getLogger(CustomerViewUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //revert cursor
            this.setCursor(Cursor.getDefaultCursor());
        } else {
            //Error message when no radio buttons are pressed
            noRadioPushed.setBounds(100, 100, 400, 150);
            noRadioPushed.setLocationRelativeTo(this);
            noRadioPushed.setVisible(true);
        }

    }//GEN-LAST:event_searchDatabasePropActionPerformed

    /*
    * @param Exit button in searchResults dialog pushed.
    * This method closes out the results dialog.
    */
    private void searchResultsExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchResultsExitActionPerformed
        searchResults.setVisible(false);
    }//GEN-LAST:event_searchResultsExitActionPerformed

    /*
    * @param Exit button in noResults dialog pushed.
    * This method closes out the no results dialog.
    */
    private void noResultsExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noResultsExitActionPerformed
        noResultsFrame.setVisible(false);
    }//GEN-LAST:event_noResultsExitActionPerformed
    
    /*
    * @param Exit button in noRadioPushed dialog pushed.
    * This method closes out the error diaglog.
    */
    private void errorExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorExitActionPerformed
        noRadioPushed.setVisible(false);
    }//GEN-LAST:event_errorExitActionPerformed

    /*
    * @param Exit button on main JFrame pushed.
    * Exits the JFrame via the exit button.
    */
    private void exitCustViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitCustViewActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitCustViewActionPerformed

    /*
    * @param the Send button for sending a message is pushed
    * Sends a message to the dealersip if all fields are filled out.
    */
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String name = namePane.getText();
        String phone = phonePane.getText();
        String email = emailPane.getText();
        String message = messagePane.getText();
        //If all fields filled out, sends message.
        if(name.length() != 0 && phone.length() != 0 && email.length() != 0 && message.length() != 0) {
            //start waiting cursor
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            dealership.getComm().sendMessage(name, phone, email, message); 
            //revert cursor
            this.setCursor(Cursor.getDefaultCursor());
            //display success message
            messageSuccess.setBounds(100, 100, 375, 175);
            messageSuccess.setLocationRelativeTo(this);
            messageSuccess.setVisible(true);
        //Field isn't filled out, display appropriate error message
        } else {
            messageFieldEmpty.setBounds(100, 100, 425, 200);
            messageFieldEmpty.setLocationRelativeTo(this);
            messageFieldEmpty.setVisible(true);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    /*
    * @param The exit button on messageFieldEmpty dialog is pressed.
    * Closes the messageFieldEmpty dialog.
    */
    private void messageFieldsEmptyExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldsEmptyExitActionPerformed
        messageFieldEmpty.setVisible(false);
    }//GEN-LAST:event_messageFieldsEmptyExitActionPerformed

    /*
    * @param exit button on messageSuccess dialog is pressed.
    * Exits the messageSuccess dialog
    */
    private void messageSuccessExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageSuccessExitActionPerformed
        messageSuccess.setVisible(false);
    }//GEN-LAST:event_messageSuccessExitActionPerformed

    /**
     * This method creates and runs the JFrame
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //Creates new thread
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerViewUI UI = new CustomerViewUI();
                //centers JFrame
                UI.setLocationRelativeTo(null);
                UI.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andLabel;
    private javax.swing.JLabel buttonErrorLabel;
    private javax.swing.JLabel buttonErrorTitle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton carRadio;
    private javax.swing.JLabel dealershipSoftwareTitle;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextPane emailPane;
    private javax.swing.JButton errorExit;
    private javax.swing.JButton exitCustView;
    private javax.swing.JTextPane highPricePane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane lowPricePane;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextPane makePane;
    private javax.swing.JLabel messageEmptyLabel;
    private javax.swing.JLabel messageEmptyTitle;
    private javax.swing.JDialog messageFieldEmpty;
    private javax.swing.JButton messageFieldsEmptyExit;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messagePane;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JDialog messageSuccess;
    private javax.swing.JButton messageSuccessExit;
    private javax.swing.JLabel messageSuccessLabel1;
    private javax.swing.JLabel messageSuccessLabel2;
    private javax.swing.JLabel messageSuccessTitle;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextPane modelPane;
    private javax.swing.JRadioButton motorRadio;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextPane namePane;
    private javax.swing.JDialog noRadioPushed;
    private javax.swing.JButton noResultsExit;
    private javax.swing.JDialog noResultsFrame;
    private javax.swing.JLabel noResultsLabel;
    private javax.swing.JLabel noResultsTitle;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextPane phonePane;
    private javax.swing.JLabel priceBetweenLabel;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton searchDatabaseProp;
    private javax.swing.JButton searchDatabaseVIN;
    private javax.swing.JLabel searchDealershipTitle;
    private javax.swing.JLabel searchDealershipTitleProp;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JDialog searchResults;
    private javax.swing.JButton searchResultsExit;
    private javax.swing.JLabel searchResultsTitle;
    private javax.swing.JSeparator searchSeparator;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel sendMessageTitle;
    private javax.swing.JRadioButton truckRadio;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextPane vinPane;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextPane yearPane;
    // End of variables declaration//GEN-END:variables
}
